name: Update README with Private Repo Stats

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour; adjust as needed
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clean Up Repository
        run: |
          # Stash any local changes
          git stash --include-untracked
          # Reset any local changes
          git reset --hard
          # Remove untracked files and directories
          git clean -fd

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch GitHub Stats from Private Repos
        env:
          IFA_GITHUB_TOKEN_PRIVATE: ${{ secrets.IFA_GITHUB_TOKEN_PRIVATE }}
        run: |
          curl -H "Authorization: Bearer $IFA_GITHUB_TOKEN_PRIVATE" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/repos?visibility=private > repos.json

          # Parse repos.json with jq
          cat repos.json | jq '[.[] | {name, language, stargazers_count}]' > stats.json

          # Format stats.json into markdown for README
          echo "# GitHub Repo Stats" > README-content.md
          cat stats.json | jq -r '.[] | "* \(.name): \(.language) - 🌟 \(.stargazers_count) stars"' >> README-content.md

      - name: Update README
        run: |
          # Append stats to README file
          cat README-content.md >> README.md
          
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # Pull latest changes to avoid conflicts
          git fetch origin
          git reset --hard origin/main
          
          # Commit and push changes
          git add README.md
          git commit -m "Update README with latest private repo stats"
          git push
